import {connect} from "react-redux";
import {itemcategory} from "../app/operations";

/**
 * created by Inspire UI @author(dang@inspireui.com)
 * @format
 */

const LOGIN_FETCHING = "user/LOGIN_FETCHING";
const LOGIN_SUCCESS = "user/LOGIN_SUCCESS";
const LOGIN_FAILURE = "user/LOGIN_FAILURE";


//Advertisements
const ADVERTISEMENT_SUCCESS = "user/ADVERTISEMENT_SUCCESS";

//offers
const OFFERS_SUCCESS = "user/OFFERS_SUCCESS";


// packages
const GET_PACKAGES_SUCCESS = "user/GET_PACKAGES_SUCCESS";


const REGISTER_FETCHING = "user/REGISTER_FETCHING";
const REGISTER_SUCCESS = "user/REGISTER_SUCCESS";
const REGISTER_FAILURE = "user/REGISTER_FAILURE";

const EDIT_PROFILE_FETCHING = "user/EDIT_PROFILE_FETCHING";
const EDIT_PROFILE_SUCCESS = "user/EDIT_PROFILE_SUCCESS";
const EDIT_PROFILE_FAILURE = "user/EDIT_PROFILE_FAILURE";

const USER_INFO_FETCHING = "user/INFO_FETCHING";
const USER_INFO_SUCCESS = "user/INFO_SUCCESS";
const USER_INFO_FAILURE = "user/INFO_FAILURE";

const ADD_PORTFOLIO_FETCHING = "user/ADD_PORTFOLIO_FETCHING";
const ADD_PORTFOLIO_SUCCESS = "user/ADD_PORTFOLIO_SUCCESS";
const ADD_PORTFOLIO_FAILURE = "user/ADD_PORTFOLIO_FAILURE";

const USER_CREATE_ADDRESS_FETCHING = "user/address/CREATE_FETCHING";
const USER_CREATE_ADDRESS_SUCCESS = "user/address/CREATE_SUCCESS";
const USER_CREATE_ADDRESS_FAILURE = "user/address/CREATE_FAILURE";

const USER_UPDATE_ADDRESS_FETCHING = "user/address/UPDATE_FETCHING";
const USER_UPDATE_ADDRESS_SUCCESS = "user/address/UPDATE_SUCCESS";
const USER_UPDATE_ADDRESS_FAILURE = "user/address/UPDATE_FAILURE";

const USER_UPDATE_DEFAULT_ADDRESS_FETCHING = "user/address/UPDATE_DEFAULT_FETCHING";
const USER_UPDATE_DEFAULT_ADDRESS_SUCCESS = "user/address/UPDATE_DEFAULT_SUCCESS";
const USER_UPDATE_DEFAULT_ADDRESS_FAILURE = "user/address/UPDATE_DEFAULT_FAILURE";

const USER_DELETE_ADDRESS_FETCHING = "user/address/DELETE_FETCHING";
const USER_DELETE_ADDRESS_SUCCESS = "user/address/DELETE_SUCCESS";
const USER_DELETE_ADDRESS_FAILURE = "user/address/DELETE_FAILURE";

const ADD_SEEKER_PROJECT_FETCHING = "user/ADD_SEEKER_PROJECT_FETCHING";
const ADD_SEEKER_PROJECT_SUCCESS = "user/ADD_SEEKER_PROJECT_SUCCESS";
const ADD_SEEKER_PROJECT_FAILURE = "user/ADD_SEEKER_PROJECT_FAILURE";


const PROJECT_LIST_FETCHING = "user/PROJECT_LIST_FETCHING";
const PROJECT_LIST_SUCCESS = "user/PROJECT_LIST_SUCCESS";
const PROJECT_LIST_FAILURE = "user/PROJECT_LIST_FAILURE";


const FREELANCER_LIST_FETCHING = "user/FREELANCER_LIST_FETCHING";
const FREELANCER_LIST_SUCCESS = "user/FREELANCER_LIST_SUCCESS";
const FREELANCER_LIST_FAILURE = "user/FREELANCER_LIST_FAILURE";


const FOLLOW_USER_FETCHING = "user/FOLLOW_USER_FETCHING";
const FOLLOW_USER_SUCCESS = "user/FOLLOW_USER_SUCCESS";
const FOLLOW_USER_FAILURE = "user/FOLLOW_USER_FAILURE";
const FAVOURITEPRODUCTS = "app/FAVOURITEPRODUCTS";
const GETSELLINGPRODUCTS = "app/GETSELLINGPRODUCTS";
const GETOFFERPRODUCTS = "app/GETOFFERPRODUCTS";
const GET_CHECKOUTS = "app/GET_CHECKOUTS";
const GET_SELLER_PRODUCTS = "app/GET_SELLER_PRODUCTS";
const GET_ALL_PRODUCTS = "app/GET_ALL_PRODUCTS";
const GET_CATEGORIES_DATA = "app/GET_CATEGORIES_DATA";

const FETCHING = "user/FETCHING";
const PATIENT_APPOINTMENTS_SUCCESS = "user/PATIENT_APPOINTMENTS_SUCCESS";
const FAILURE = "user/FAILURE";
const POST_ITEM_SUCCESS ="user/POST_ITEM_SUCCESS";
const POST_ITEM_FAILURE ="user/POST_ITEM_FAILURE";

const SAVE_ONLINE_DOCTORS = "user/SAVE_ONLINE_DOCTORS";

const LOGOUT = "user/LOGOUT";





//chat work
const GET_CHAT_ROOM_LIST = "user/GET_CHAT_ROOM_LIST";
const GET_ALL_CHAT = "user/GET_ALL_CHAT";

export {
    PATIENT_APPOINTMENTS_SUCCESS,
    FETCHING,
    FAILURE,
    LOGIN_FETCHING,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    REGISTER_FETCHING,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    USER_INFO_FETCHING,
    USER_INFO_SUCCESS,
    USER_INFO_FAILURE,
    USER_CREATE_ADDRESS_FETCHING,
    USER_CREATE_ADDRESS_SUCCESS,
    USER_CREATE_ADDRESS_FAILURE,
    USER_UPDATE_ADDRESS_FETCHING,
    USER_UPDATE_ADDRESS_SUCCESS,
    USER_UPDATE_ADDRESS_FAILURE,
    USER_UPDATE_DEFAULT_ADDRESS_FETCHING,
    USER_UPDATE_DEFAULT_ADDRESS_SUCCESS,
    USER_UPDATE_DEFAULT_ADDRESS_FAILURE,
    USER_DELETE_ADDRESS_FETCHING,
    USER_DELETE_ADDRESS_SUCCESS,
    USER_DELETE_ADDRESS_FAILURE,
    EDIT_PROFILE_FETCHING,
    EDIT_PROFILE_SUCCESS,
    EDIT_PROFILE_FAILURE,
    ADD_PORTFOLIO_FETCHING,
    ADD_PORTFOLIO_SUCCESS,
    ADD_PORTFOLIO_FAILURE,
    ADD_SEEKER_PROJECT_FETCHING,
    ADD_SEEKER_PROJECT_SUCCESS,
    ADD_SEEKER_PROJECT_FAILURE,
    PROJECT_LIST_FETCHING,
    PROJECT_LIST_SUCCESS,
    PROJECT_LIST_FAILURE,
    FREELANCER_LIST_FETCHING,
    FREELANCER_LIST_SUCCESS,
    FREELANCER_LIST_FAILURE,
    FOLLOW_USER_FETCHING,
    FOLLOW_USER_SUCCESS,
    FOLLOW_USER_FAILURE,
    SAVE_ONLINE_DOCTORS,
    POST_ITEM_SUCCESS,
    POST_ITEM_FAILURE,
    LOGOUT,
    FAVOURITEPRODUCTS,
    GETOFFERPRODUCTS,
    GETSELLINGPRODUCTS,
    GET_CHECKOUTS,
    GET_SELLER_PRODUCTS,

    GET_CHAT_ROOM_LIST,
    GET_ALL_CHAT,
    GET_CATEGORIES_DATA,
    GET_ALL_PRODUCTS,
    ADVERTISEMENT_SUCCESS,
    OFFERS_SUCCESS,
    GET_PACKAGES_SUCCESS




};
